exec(open('/tmp/claude-0/-home-user-Amy-portfolio/2b4f3ce3-d4ad-5be4-9b15-7ee08bf2127f/scratchpad/m8common.py').read())
TE, DTE = '#0F7C7A', '#0B3B45'
wv = ''
for k in range(26):
    y = 40 + k * 22
    a = 10 + 14 * math.sin(k / 26 * math.pi)
    pts = ' '.join(f'{x},{y + a * math.sin(0.012 * x + k * 0.5):.1f}' for x in range(0, 1930, 12))
    wv += f'<polyline points="{pts}" fill="none" stroke="rgba(255,255,255,.08)" stroke-width="1.2"/>'
sum17 = ('Among 1,200 post-operative patients in a study we cited, 15% experienced complications related to being transferred, and different moving devices and transition times influence secondary injury. Curawave is a mattress that imitates the movement of ocean waves to transfer patients safely and comfortably without human labour. It is built from 18 × 20 small soft units, each with a hollow silicone inflation layer, a non-stretchable cotton confining layer and a silicone base. Because the confining layer stretches less than the inflation layer, each unit tilts sideways, left or right, when inflated; adjacent units are grouped and inflated alternately, so a sideways wave slides the patient horizontally off one bed and onto the next, with no one lifting. We modelled the moulds in Autodesk Fusion, 3D-printed them, cast the silicone units, and drove an air pump through solenoid valves controlled by an Arduino, producing a working 1 × 4 prototype.')
steps = [('①', 'Mould modelling', 'Autodesk Fusion: two bases, top and bottom, and an inner core.'),
         ('②', 'One unit, tested', 'Moulds 3D-printed; silicones of different thickness poured and compared.'),
         ('③', 'Valves + code', 'Solenoid valves open and close the air pump; an Arduino program times them.'),
         ('④', '1 × 4 model', 'The main pump\'s air is split four ways, each group switched by its own valve.'),
         ('⑤', 'Further testing', 'Units tested in sequence to tune timing and inflation.')]
stp = ''.join(f'<div style="border-top: 3px solid {TE}; padding-top: 8px"><div class="pf" style="font-size: 30px; line-height: 1; color: {TE}">{n}</div><div class="lbl" style="color: {INK}; padding-top: 4px">{t}</div><div class="sr" style="font-size: 13px; line-height: 1.42; color: #333; padding-top: 4px">{d}</div></div>' for n, t, d in steps)
body17 = f"""<div style="position: absolute; left: 0; top: 0; width: 1920px; height: 600px; background: {DTE}; overflow: hidden"><svg width="1920" height="600" viewBox="0 0 1920 600" style="position: absolute; left: 0; top: 0" aria-hidden="true">{wv}</svg></div>
<div class="m" style="position: absolute; left: 56px; top: 34px; right: 56px; display: flex; justify-content: space-between; font-size: 11px; color: #BFE6E2"><span>05 — Mind · Research Nº 04 · Conrad Challenge · Beijing Lingtong Future Technology</span><span>Amy Hu · 19</span></div>
<div style="position: absolute; left: 56px; top: 70px; width: 470px; display: flex; flex-direction: column; gap: 12px; color: #FFFFFF">
<div class="pf" style="font-size: 36px; line-height: 1.07; font-weight: 900">Curawave: A <span style="color: #8FE3D8; font-style: italic">Wave-Bionic Soft Robotic Mattress</span> for Post-Operative Patient Transfer</div>
<div class="sr" style="font-size: 15px; line-height: 1.4; font-style: italic; color: #BFE6E2"><b style="font-style: normal; color: #FFFFFF">Design question.</b> Can a mattress slide a patient sideways onto another bed the way a wave moves a boat, safely and without anyone lifting?</div>
<div class="m" style="font-size: 10.5px; color: #BFE6E2">Amy Hu, CTO · with Emily Feng (CEO) and Galatea Shang (CFO)</div>
<div style="border-left: 4px solid #8FE3D8; padding-left: 14px"><div class="lbl" style="color: #8FE3D8">As CTO and founder</div><div class="sr" style="font-size: 13.5px; line-height: 1.45; padding-top: 4px">I led the technology: mould design, silicone casting, valves and Arduino control. My startup, Beijing Lingtong Future Technology, raised over USD 100k to develop assistive products (p. 20).</div></div>
<div class="lbl" style="color: #8FE3D8; padding-top: 4px">Why I built it</div><div class="sr" style="font-size: 13.5px; line-height: 1.5; color: #E6F4F2; text-align: justify">The idea began with my own bicycle accident. With an injured leg I struggled to move from place to place, and every attempt was shocked by pain. Moving patients after surgery is the same problem at hospital scale: in 2024 China had about 70 million people bedridden by injury and 96.4 million surgical operations.</div>
</div>
<div style="position: absolute; left: 560px; top: 70px; width: 800px; display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 9px">
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/3fe846081feceada66bb7a9a315f0bbb" alt="Curawave logo" style="width: 100%; height: 100%; object-fit: contain; background: #0E1416; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">01 · Logo</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/10707fb892dab0738a773f43c4dfd044" alt="Brand: Safe Transfers, Gentle Waves, Comfort for Every Patient" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">02 · Brand</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/9da752588173f1a62dcf0bc8e400949d" alt="Our website and Bilibili account" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">03 · Website &amp; Bilibili</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/81d746a8e783ab9a56af707e742bd8a7" alt="Product layers of a unit" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">04 · Product layers</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/4a4faf21f4aec5efd6db1c29e37609e6" alt="Mattress composed of 18 by 20 units" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">05 · 18 × 20 units</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/8a03b2a60b17c157d8651bc8af46d0d5" alt="Market scale slide" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">06 · Market scale</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/e14d73a7e276674ed92f265e638e1702" alt="Financial analysis slide" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">07 · Five-year finances</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/3a27d7cfbe42966a2b374683970093b2" alt="Business strategy slide" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">08 · Business strategy</div></div>
<div style="position: relative; height: 146px; overflow: hidden; background: #0E1416"><img src="/_blob/b398dac4ee3788d9ace7f1a671ea92ce" alt="Marketing plan slide" style="width: 100%; height: 100%; object-fit: cover; display: block"><div class="m" style="position: absolute; left: 0; bottom: 0; background: rgba(11,59,69,.92); color: #FFFFFF; font-size: 9.5px; padding: 4px 8px">09 · Marketing plan</div></div>
</div>
<div class="fcap" style="position: absolute; left: 560px; top: 540px; width: 800px; color: #BFE6E2">Fig. 1 · From our pitch deck: the brand and channels, the product, the market, five-year finances, strategy and the marketing plan we built as a team.</div>
<div class="abs" style="position: absolute; left: 1394px; top: 70px; width: 470px; color: #FFFFFF; border-top: 1px solid rgba(255,255,255,.5); padding-top: 10px"><b>Summary</b> &nbsp;{sum17}</div>
<div style="position: absolute; left: 1394px; top: 372px; width: 470px; display: grid; grid-template-columns: 1fr 1fr; gap: 22px; color: #FFFFFF">
<div><div class="lbl" style="color: #8FE3D8">Market &amp; plan</div><div class="sr" style="font-size: 13px; line-height: 1.45; padding-top: 4px; color: #E6F4F2">China's medical-device market is about 120 billion yuan. We start with first-tier hospitals: direct sales, training videos and yearly maintenance. Forecast turnover grows from ¥2.3M to ¥21.6M in five years, with 1% to charity.</div></div>
<div><div class="lbl" style="color: #8FE3D8">Next steps</div><div class="sr" style="font-size: 13px; line-height: 1.45; padding-top: 4px; color: #E6F4F2">AI that reads the forces on a patient and adjusts each unit's inflation; a patent on how the units are assembled to mimic waves; and markets beyond mainland China.</div></div>
</div>
<div style="position: absolute; left: 56px; top: 630px; width: 1000px; display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 18px">{stp}</div>
<div style="position: absolute; left: 56px; top: 792px; width: 1000px; display: flex; gap: 14px; align-items: baseline; border-top: 1px solid #1A1A1A; padding-top: 8px"><span class="lbl" style="color: #0F7C7A; white-space: nowrap">Innovations</span><span class="sr" style="font-size: 13.5px; line-height: 1.45; color: #333">Transfers patients sideways from bed to bed with no lifting · massages patients who cannot move, such as those in a vegetative state · waterproof, bacteria-resistant and easy to clean · lower price than existing transfer devices.</span></div>
<div style="position: absolute; left: 1090px; top: 630px; width: 774px; display: grid; grid-template-columns: 1.15fr 1fr 1fr; gap: 16px">
{fig('1363b697e6a919f12f15c326765bb5ce', 'Moving principle of a single unit', 'Fig. 2 · How one unit tilts sideways and pushes.', style='height: 180px; object-fit: contain; background: #FFFFFF')}
{fig('9d8e6e3557fbd85611fe80cffbd26e34', 'Cast silicone units', 'Fig. 3 · Cast silicone units.', style='height: 180px; object-fit: cover')}
{fig('b6452e51a792537939c82674dd762b74', 'Pump, solenoid valves and Arduino wiring', 'Fig. 4 · Pump, valves and Arduino.', style='height: 180px; object-fit: cover')}
</div>
""" + kws([('$100k+', 'raised for my assistive-tech startup'), ('3+', 'wave-mattress prototypes'), ('10+', 'CAD and circuit designs'),
          ('20+', 'parts 3D-printed or cast'), ('100+', 'people pitched to'), ('2', 'products: hearing aids &amp; mattress')], 56, 1808, 26)
write('Mind-Curawave.dc.html', 'Curawave', PAPER, body17)
