exec(open('/tmp/claude-0/-home-user-Amy-portfolio/2b4f3ce3-d4ad-5be4-9b15-7ee08bf2127f/scratchpad/m8common.py').read())
BL, AC1, AC2 = '#1B2FA8', '#D9432E', '#1B2FA8'
def eq(t, acc):
    return f'<div class="ef" style="border-top: 2px solid {acc}; background: #FFFFFF; padding: 8px 10px; font-family: \'Source Serif 4\',serif; font-style: italic; font-size: 14px; text-align: center; color: {INK}">{t}</div>'
ED = secs(AC1, [
    ('1 · The physics', '<p class="dc">A magnet hanging on a spring oscillates inside a coil wired to a resistor. As it moves, the changing flux induces an emf; the induced current feels an Ampère force that pushes back on the magnet, and its energy leaves as Joule heat in the resistor. Damping is therefore a chain: mechanical energy → electrical energy → heat. In a preliminary run (R = 10 Ω, N = 400 turns, μ = 27.02 A·m²) the amplitude decayed exponentially, and damping was slightly stronger when the magnet was near the coil\'s edge.</p>'),
    ('2 · Model', '<p>I modelled the bar magnet as an equivalent current sheet (measured magnetisation M = (1.12 ± 0.04) × 10<sup>6</sup> A/m) and integrated Biot–Savart over the coil to get the flux ψ(x, N, B) and the mutual-inductance gradient G = dψ/dx, so ε = G ẋ. Kirchhoff and Newton then couple the circuit to the motion:</p>'
     + eq(f'G ẋ = L İ + I R<br>m ẍ = −k(x − x<sub>0</sub>) − mg + I G − 2mγ<sub>mech</sub>ẋ<br><span style="font-size: 12.5px">ignoring inductance: F<sub>em</sub> = −(G²/R) ẋ, &nbsp;γ<sub>em</sub> = G²/R</span>', AC1)
     + '<p>Solved with RK4, the motion is underdamped; an FFT of the current shows several superposed frequencies, because the magnet\'s field has strong nonlinear terms.</p>'),
    ('3 · Predictions', '<p>Turns: damping rises quickly up to a peak at 2,700 ± 10 turns, then slowly falls to 6,000 turns as the coil\'s own inductive reactance chokes the current. Resistance: damping falls roughly as 1/R. Magnetic moment: since ε ∝ m and F ∝ I·m, damping first grows quadratically, then levels off as the heavier magnet gains inertia.</p>'),
    ('4 · Experiment', fig('cfcb2496788f397440d44ba3069cb55d', 'Electrical damping rig: spring, magnet, coil, resistance box and data logger', 'Fig. 1 · My rig: spring and N52 magnet, coil, resistance box, galvanometer, displacement sensor.', style='height: 178px; object-fit: contain')
     + '<p>Spring 16 N/m; total mass 0.05 kg; N52 cylinder magnet 8 mm × 12 mm; coil 2,666.67 turns/m. I varied turns (200, 800, 1,600), magnets (2–16) and resistance (2–10 Ω), tracked the motion on video with Tracker and logged current. With the circuit open, mechanical damping was γ<sub>mech</sub> = 0.0162 ± 0.0005; at Re ≈ 183 air drag is linear, so it could be subtracted cleanly.</p>'),
    ('5 · Results', figh('<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 6px"><img src="/_blob/7230a027da56dd3103799ace1144deca" alt="Damping coefficient against coil turns, model and data"><img src="/_blob/4093260356b152bcfd4fe9f3f2f844ca" alt="Damping coefficient against resistance"><img src="/_blob/ab945b6bc71fb90fce621070e047cc41" alt="Damping coefficient against magnetic moment"></div>', 'Fig. 2 · γ against turns, resistance and magnetic moment: model (line) and my data (points).')
     + '<p>All three trends match the model. Errors: a 3.6% magnetisation error doubles to 7.2% in damping (F ∝ M²); inductance carries 10%; large amplitudes push the spring past linearity, and a slight swing or spin of the magnet changes dψ/dt.</p>'),
])
LV = secs(AC2, [
    ('1 · The physics', '<p class="dc">Pyrolytic graphite is diamagnetic, so it floats above the potential minimum of a checkerboard of NdFeB magnets. A laser spot heats one edge; graphite\'s susceptibility depends on temperature, so the force on the sheet becomes uneven and it tilts and slides. Depending on laser power and speed, it stays levitated, relaxes back, or follows the light continuously.</p>'
     + figh('<div style="display: grid; grid-template-columns: 1.25fr 0.62fr; grid-template-rows: 64px 64px; gap: 5px"><img src="/_blob/0d10a151e3d46fb51523fa00009522f9" alt="Laser module on a 2-D gantry over the magnet array" style="height: 64px; object-fit: cover"><img src="/_blob/b9d4757488d9104b67b3aa9ee2faef65" alt="3D printer printing holders" style="grid-row: span 2; height: 133px; object-fit: cover"><img src="/_blob/262dbeea3bd5826e7d9b1b9c2ebfec11" alt="Graphite sheet floating on four magnets" style="height: 64px; object-fit: cover"></div>', 'Fig. 3 · Equipment I bought and set up: the laser on a 2-D gantry, my 3D printer making holders, and graphite floating on my magnets.')),
    ('2 · Field and force', '<p>For an m × n array of alternating cubic magnets I built the field from surface currents (J = 3.651 × 10<sup>5</sup> A/m²) by Biot–Savart and superposition. With anisotropic χ (χ<sub>∥</sub>, χ<sub>⊥</sub>) and χ ≪ 1, the energy density is u = −χB²/2μ<sub>0</sub>. Levitation balances ρg = (χ<sub>⊥</sub>/μ<sub>0</sub>) B<sub>z</sub> ∂B<sub>z</sub>/∂z; the periodic array term cancels over a cycle, leaving the light-driven term:</p>'
     + eq(f'F<sub>r</sub> = (h / 2μ<sub>0</sub>) · (dχ<sub>∥</sub>/dT) · (dT/dr) · ∬ B<sub>xy</sub>² dA', AC2)
     + '<p>From the Landau free energy, χ depends on temperature; I used the measured χ<sub>⊥</sub> = (−743 + T) × 10<sup>−6</sup> and χ<sub>∥</sub> = (−135 + 0.25T) × 10<sup>−6</sup>.</p>'),
    ('3 · Temperature field', '<p>A 3-D transient heat equation with a Gaussian spot gives the surface temperature. At 300 mW the gradient is constant from 0.05 s on, with ΔT = 1.36 K across the sheet.</p>'
     + figh('<div style="display: grid; grid-template-columns: 1fr 1.1fr; gap: 6px; align-items: center"><img src="/_blob/e9dce5de17c6f63db10e0608e3af1f07" alt="Thermal camera image of the heated graphite"><img src="/_blob/9f674d05047845230907795f42b6ced4" alt="Maximum and minimum sheet temperature over time"></div>', 'Fig. 4 · My thermal-camera image of the heated sheet; model: hottest and coolest points under 300 mW.')),
    ('4 · Motion', '<p>Newton\'s law m r̈ = F<sub>r</sub> − F<sub>k</sub> − ζṙ combines light drive, a restoring force from the array\'s potential (periodic with the magnet edge l) and thin-film air drag. If F<sub>r</sub> ≤ F<sub>k,max</sub> + drag the sheet relaxes within one period l; above it, it moves continuously.</p>'
     + figh('<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 6px; align-items: center"><img src="/_blob/5a524f990cbabf66c9e8a4736ca56805" alt="Model: levitation height against remanence"><img src="/_blob/71a59e58106f8bd4765319e61771694b" alt="Potential energy of the sheet along the array"></div>', 'Fig. 5 · Model: levitation height against remanence; the potential along the array repeats with the magnet edge l.')),
    ('5 · Experiment, honestly', '<p>Magnets of 10 and 5 mm at 0.1–0.4 T, graphite 0.3 mm and 50 µm, a 0–1.6 W laser on a 2-D gantry and a thermal camera. The sheet levitated and heated as predicted, but my set-up did not yet reproduce light-driven travel. My analysis: N52 magnets hold the sheet too firmly for a 1.6 W beam. Next: weaker magnets, thinner graphite, more power.</p>'),
])
ph = lambda h, t: f'<div style="height: {h}px; border: 1.5px dashed rgba(255,255,255,.7); display: flex; align-items: center; justify-content: center; text-align: center; padding: 10px; font-family: \'IBM Plex Mono\',monospace; font-size: 10.5px; letter-spacing: .08em; text-transform: uppercase; color: rgba(255,255,255,.85)">{t}</div>'
body = f"""<div style="position: absolute; left: 790px; top: 0; width: 340px; height: 960px; background: {BL}"></div>
<div class="m" style="position: absolute; left: 56px; top: 34px; width: 704px; display: flex; justify-content: space-between; font-size: 11px; color: {AC1}; border-bottom: 2px solid {INK}; padding-bottom: 6px"><span>05 — Mind · Research Nº 01 · CYPT 2026 · problem 2</span><span>Beijing 101 High School</span></div>
<div class="m" style="position: absolute; left: 1160px; top: 34px; width: 704px; display: flex; justify-content: space-between; font-size: 11px; color: {AC2}; border-bottom: 2px solid {INK}; padding-bottom: 6px"><span>CYPT 2026 · problem 9</span><span>Amy Hu · 16</span></div>
<div style="position: absolute; left: 56px; top: 66px; width: 704px; color: {INK}">
<div class="pf" style="font-size: 40px; line-height: 1.05; font-weight: 900">Electrical <span style="color: {AC1}; font-style: italic">Damping</span></div>
<div class="sr" style="font-size: 14px; line-height: 1.42; font-style: italic; color: #444; padding-top: 6px"><b style="font-style: normal; color: {INK}">Problem.</b> A magnet suspended by a spring will display simple harmonic motion when displaced. If the magnet oscillates within a coil connected to a resistor, its motion will be damped. Investigate the factors that affect the damping.</div></div>
<div class="col" style="position: absolute; left: 56px; top: 196px; width: 704px; height: 668px; column-count: 2; column-fill: auto; column-gap: 24px; color: {INK}">{ED}</div>
<div style="position: absolute; left: 1160px; top: 66px; width: 704px; color: {INK}">
<div class="pf" style="font-size: 40px; line-height: 1.05; font-weight: 900">Levitation <span style="color: {AC2}; font-style: italic">Control</span></div>
<div class="sr" style="font-size: 14px; line-height: 1.42; font-style: italic; color: #444; padding-top: 6px"><b style="font-style: normal; color: {INK}">Problem.</b> When arranged in a specific configuration, small graphite sheets can levitate on neodymium magnets. By shining light onto the surface of the graphite sheet, it is possible to control its movement. Explain and investigate the phenomenon.</div></div>
<div class="col" style="position: absolute; left: 1160px; top: 196px; width: 704px; height: 668px; column-count: 2; column-fill: auto; column-gap: 24px; color: {INK}">{LV}</div>
<div style="position: absolute; left: 816px; top: 34px; width: 288px; display: flex; flex-direction: column; gap: 12px; color: #FFFFFF">
<div class="m" style="font-size: 11px; color: #C9D2FF">CYPT 2026 · team captain</div>
<div class="pf" style="font-size: 30px; line-height: 1.05; font-weight: 900">Three problems, <span style="font-style: italic; color: #FFB4A3">one team</span></div>
<div class="sr" style="font-size: 13px; line-height: 1.5; text-align: justify; color: #E4E8FF">Besides the magnetic cradle on the previous page, I reported these two problems myself. As captain I led our team\'s discussions: we took each problem apart into physics, model and experiment, argued over every assumption, and rehearsed the opposition and review rounds together before the tournament.</div>
<div style="position: relative"><img src="/_blob/d2ec2ab3b9e180a9da7ba7c15b117b90" alt="Amy leading a team discussion around a laptop" style="width: 100%; height: 150px; object-fit: cover; display: block"><div class="fcap" style="color: #C9D2FF; padding-top: 3px">Leading a team discussion before the fights.</div></div>
<div style="position: relative"><img src="/_blob/b1d57a32fae921a361a0141bf275e539" alt="Amy presenting Electrical Damping in a classroom" style="width: 100%; height: 150px; object-fit: cover; display: block"><div class="fcap" style="color: #C9D2FF; padding-top: 3px">Reporting Electrical Damping.</div></div>
<div style="position: relative"><img src="/_blob/902f4b8eadf7d605c3b2371a47331b3e" alt="The team working at laptops during CYPT 2026" style="width: 100%; height: 216px; object-fit: cover; display: block"><div style="position: absolute; left: 9%; top: 1%; display: flex; flex-direction: column; align-items: center"><span class="m" style="background: #FFB4A3; color: #1B2FA8; font-size: 9.5px; font-weight: 500; padding: 2px 6px">Me</span><span style="width: 0; height: 0; border-left: 5px solid transparent; border-right: 5px solid transparent; border-top: 7px solid #FFB4A3"></span></div><div class="fcap" style="color: #C9D2FF; padding-top: 3px">The whole team at CYPT 2026; I am the one with the red hair tie.</div></div>
</div>
"""
body += kws([("2,700", "turns: predicted damping peak"), ("1/R", "damping vs resistance, confirmed"), ("7.2%", "largest error, traced to M²")], 56, 704, 22, col=AC1) + kws([("1.36 K", "light-made gradient across the sheet"), ("4", "coupled models: field, χ(T), heat, motion"), ("1.6 W", "laser limit I must beat next")], 1160, 704, 22, col=AC2)
write('Mind-CYPT.dc.html', 'CYPT problems', PAPER, body)
