exec(open('/tmp/claude-0/-home-user-Amy-portfolio/2b4f3ce3-d4ad-5be4-9b15-7ee08bf2127f/scratchpad/m8common.py').read())
OR, DGR_ = '#C4521F', '#1D2226'
abs18 = ('Bulk metallic glasses (BMGs) represent a unique class of materials that combine the disordered atomic structure of glass with the properties of metals. Their response to dynamic loading, such as high-velocity impact, is not only crucial for potential structural applications but also fundamental to understanding non-crystalline physics. Crystalline metals show a counterintuitive phonon-drag strengthening effect under high strain rates at high temperatures, which contrasts with glasses\' conventional thermal softening behaviour. Therefore, whether BMGs exhibit a similar phenomenon remains an open question. In this work, the impact response of a Pd<sub>43</sub>Ni<sub>10</sub>Cu<sub>27</sub>P<sub>20</sub> BMG at 25 °C, 100 °C and 200 °C was investigated via laser-induced particle impact tests and finite element method simulations. In-situ observation revealed a significant enhancement in energy dissipation of BMGs at 200 °C. Post-impact characterization identified a transition in deformation mechanism: solid-like craters with minimal pile-up at 25 °C gave way to fluid-like, irregular pile-up morphologies at 200 °C, suggesting adiabatic heating-induced softening. A calculated ~10.4% reduction in dynamic yield strength at high temperature provided quantitative confirmation of this thermal softening. Furthermore, simulations incorporating a physical constitutive model successfully replicated the experimental results and uncovered the underlying mechanism: high temperature promotes the activation of shear transformations, leading to greater plastic flow and prolonged impact interaction time. This study conclusively demonstrates that temperature is a critical, governing factor for the dynamic performance of BMGs, challenging simplistic material selection and providing vital insights for their application in extreme environments. <i style="color: #C4521F">Key words: micro-particle impact, metallic glass, temperature, plastic flow, energy dissipation.</i>')
SECS18 = secs(OR, [
    ('1 · Background', '<p class="dc">Glass is a solid at room temperature but behaves like a super-viscous liquid when hot, because its atoms are arranged with "short-range order and long-range disorder". Metals are crystalline, with long-range periodic order that gives them strength and ductility. Metallic glass combines the two: molten metal is cooled so fast that its atoms have no time to crystallise, freezing the disordered liquid structure into a solid.</p><p>Under impact, ordinary glass shatters while metal deforms plastically. Recent work showed that at strain rates above 10<sup>4</sup> s<sup>−1</sup> pure metals (Cu, Au, Ti) become <i>stronger</i> as temperature rises, through phonon drag. Would a metallic glass harden like a metal, or soften like a glass?</p>'),
    ('2 · Sample', '<p>Pd<sub>43</sub>Ni<sub>10</sub>Cu<sub>27</sub>P<sub>20</sub> was chosen for its low critical cooling rate and high amorphous stability. Samples (10 × 5 × 3 mm³) were wire-cut with a diamond saw, ground, polished and mounted on a heated glass plate. XRD showed only one broad hump near 40° and no sharp peaks, confirming the glassy state; DSC gave T<sub>g</sub> = 570 K and crystallisation at 632 K, so 25–200 °C keeps the sample amorphous.</p>'
     + fig('b7c6ac1ec555a94567bc99f5820e7b35', 'XRD instrument and XRD pattern with TEM inset', 'Fig. 1 · a XRD set-up; b one broad amorphous hump, TEM inset.', style='max-height: 118px; width: auto; margin: 0 auto')),
    ('3 · LIPIT platform', '<p>A 7 ns, 532 nm pulsed laser is focused through a convex lens onto a launch pad: 4 mm K9 glass, a 100 nm gold ablation layer and an 80 µm polymer elastic layer carrying 30 µm SiO<sub>2</sub> particles. The expanding plasma flings a particle at 1–1000 m/s; a camera at up to 5,000,000 fps records it. A REX-C900 PID controller holds the target from 25 to 400 °C within ±1 K. Craters were then imaged by SEM and their depth profiled by laser confocal microscopy.</p>'),
    ('4 · Energy dissipation', '<p>From impact speed v<sub>i</sub> and rebound speed v<sub>r</sub>, COR = v<sub>r</sub>/v<sub>i</sub>. At 200 °C the COR is consistently lower: the hot glass dissipates more energy, the cold glass resists penetration better. Between 80 and 250 m/s both follow COR ∝ v<sub>i</sub><sup>−0.5</sup> (finite plasticity: 8.6 v<sub>i</sub><sup>−0.5</sup> at 25 °C, 7.7 v<sub>i</sub><sup>−0.5</sup> at 200 °C); above 250 m/s they fall more steeply, 140 v<sub>i</sub><sup>−1</sup> against 372 v<sub>i</sub><sup>−1.2</sup>.</p>'
     + fig('0f1e5bcc281d446411ef773b7ef5aef2', 'Coefficient of restitution against impact velocity at 25 and 200 °C', 'Fig. 2 · COR against impact velocity, 25 °C (black) and 200 °C (red).', style='max-height: 128px; width: auto; margin: 0 auto')),
    ('5 · Dynamic yield strength', '<p>In the finite-plastic regime, Wu\'s relation COR = α[(v<sub>i</sub>/v<sub>y</sub>)/(E*/Y<sub>d</sub>)]<sup>−1/2</sup> with α = 0.78 and Johnson\'s yield velocity v<sub>y</sub> can be solved for Y<sub>d</sub>. The result: 2089 ± 110 MPa at 25 °C, about 1901 MPa at 100 °C and 1825 ± 65 MPa at 200 °C, a fall of <b>10.39%</b>. The glass softens: it trades impact resistance for energy dissipation.</p>'
     + figh(f'<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 6px"><img src="/_blob/381a10a7cf63614d542cff98bad4bf00" alt="Rebound velocity and dynamic yield strength at 25 °C"><img src="/_blob/fa17158e42feaa9e2924c2a55a063217" alt="Rebound velocity and dynamic yield strength at 200 °C"></div>', 'Fig. 3 · Y<sub>d</sub> at 25 °C (left) and 200 °C (right).')),
    ('6 · Simulation', '<p>To see the mechanism, I built a quarter-symmetric ABAQUS model (about 1.35 million C3D8I elements, 0.25 µm at the contact) with a coupled shear-transformation-zone / free-volume constitutive model. Its crater profile matched the confocal measurement at 300 m/s. At 400 m/s the deepest indentation came at 14.4 ns (25 °C) against 15.2 ns (200 °C), and separation at 23.6 against 25.6 ns: a longer contact, lower stress, greater plastic strain, and many more positive shear transformations at 200 °C.</p>'
     + fig('3b81ff73871769680794fbe3b7ea396d', 'Field-averaged stress, plastic strain and STZ densities', 'Fig. 4 · Field-averaged stress, plastic strain and STZ densities; red 200 °C, blue 25 °C.', style='max-height: 125px; width: auto; margin: 0 auto')),
    ('7 · Limitations', '<p>Yield stress is inferred, not measured, so small velocity errors grow through v². Thermal gradients mean the true impact temperature is unknown, and adiabatic heating could not be measured. Above T<sub>g</sub> the surface oxidised badly (we tried a vacuum, but the chamber needed was too large), so the range stopped at 200 °C.</p>'),
    ('8 · Conclusion', '<p>Temperature governs how a metallic glass meets an impact: from solid-like to fluid-like, with 10.4% lower dynamic yield strength and more energy absorbed. Unlike crystalline metals, it does not harden when hot.</p>'),
])
band = f"""<div style="position: absolute; left: 0; top: 722px; width: 1920px; height: 238px; background: {DGR_}"></div>
<div style="position: absolute; left: 56px; top: 738px; width: 1808px; display: flex; gap: 20px; align-items: flex-start; color: #FFFFFF">
<div><div style="display: flex; gap: 10px"><img src="/_blob/c3401b0e4a6dd320fe1d1d0d582fde62" alt="SEM image of a crater at 25 °C, 650 m/s" style="width: 112px; height: 112px; object-fit: cover; display: block"><img src="/_blob/d5cdc3ff88631e74d766faf945a07264" alt="SEM image of a crater at 200 °C, 643 m/s" style="width: 112px; height: 112px; object-fit: cover; display: block"></div><div class="fcap" style="color: #D7D0C8; width: 234px">Fig. 5 · SEM craters, 25 °C vs 200 °C.</div></div>
<div><div style="display: flex; flex-direction: column; gap: 4px; background: #FFFFFF; padding: 4px"><img src="/_blob/e85290532720f4ffa1b1fc74f115d640" alt="High-speed frames at 25 °C" style="height: 51px; display: block"><img src="/_blob/f9e5e43aaaa4e85f6cad74af0030e80d" alt="High-speed frames at 200 °C" style="height: 51px; display: block"></div><div class="fcap" style="color: #D7D0C8; width: 270px">Fig. 6 · High-speed frames, 25 °C and 200 °C.</div></div>
<div><div style="background: #FFFFFF; padding: 4px"><img src="/_blob/4304437a3dae5015ee104c3c7cfe8ceb" alt="Simulated indentation at characteristic times" style="height: 104px; display: block"></div><div class="fcap" style="color: #D7D0C8; width: 170px">Fig. 7 · FEM indentation, 400 m/s.</div></div>
<div><img src="/_blob/6c5b7508c3827167ed71b6df53fc033e" alt="The LIPIT platform in the lab" style="width: 150px; height: 112px; object-fit: cover; display: block"><div class="fcap" style="color: #D7D0C8; width: 150px">Fig. 8 · The LIPIT rig I ran.</div></div>
<div style="flex: 1; display: flex; flex-direction: column; gap: 8px">
<div style="border-left: 4px solid {OR}; padding-left: 14px"><div class="lbl" style="color: #F2A16E">My role</div><div class="sr" style="font-size: 12.5px; line-height: 1.4; padding-top: 2px">First author. I prepared and characterised every sample, ran the LIPIT impacts at all three temperatures, computed COR and yield strength, and built the ABAQUS simulation with a PhD mentor in Prof. Minqiang Jiang's group.</div></div>
<div style="border-left: 4px solid {OR}; padding-left: 14px"><div class="lbl" style="color: #F2A16E">Why I asked</div><div class="sr" style="font-size: 12.5px; line-height: 1.4; padding-top: 2px; font-style: italic">"In middle school I learned that glass has no melting point. When hit, would a metallic glass shatter like glass, or flow like metal?"</div></div>
</div>
</div>
""" + kws([('100+', 'impact tests on metallic glass'), ('5 Mfps', 'high-speed camera'), ('3', 'temperatures: 25, 100, 200 °C'), ('−10.39%', 'dynamic yield strength'), ('1.35 M', 'elements in my FEM model'), ('ISEF', 'Beijing qualifier · first author')], 56, 1808, 24, col='#FFFFFF')
body18 = f"""<div class="m" style="position: absolute; left: 56px; top: 34px; right: 56px; display: flex; justify-content: space-between; font-size: 11px; color: {OR}; border-bottom: 2px solid {INK}; padding-bottom: 6px"><span>05 — Mind · Research Nº 03 · Chinese Academy of Sciences, Institute of Mechanics</span><span>Amy Hu · 18</span></div>
<div style="position: absolute; left: 56px; top: 74px; width: 560px; display: flex; flex-direction: column; gap: 12px; color: {INK}">
<div class="pf" style="font-size: 36px; line-height: 1.06; font-weight: 900">Flowed Metal: <span style="color: {OR}; font-style: italic">Micro-particle Impacts on Metallic Glasses</span> under High Temperature</div>
<div class="sr" style="font-size: 15px; line-height: 1.4; font-style: italic; color: #444"><b style="font-style: normal; color: {INK}">Research question.</b> When a metallic glass is hit at hundreds of metres per second, does heat make it harder, like a metal, or softer, like a glass?</div>
<div class="m" style="font-size: 10.5px; color: #555">Amy (Wanying) Hu, first author · supervisor Prof. Minqiang Jiang · spacecraft solid mechanics research intern</div>
</div>
<div class="abs" style="position: absolute; left: 650px; top: 78px; width: 1214px; column-count: 2; column-gap: 30px; color: {INK}; border-top: 1px solid {INK}; padding-top: 8px; font-size: 12.5px; line-height: 1.42"><b style="color: {OR}">Abstract</b> &nbsp;{abs18}</div>
<div class="col" style="position: absolute; left: 56px; top: 296px; width: 1808px; height: 412px; column-count: 5; column-fill: auto; column-gap: 26px; color: {INK}">{SECS18}</div>
""" + band
write('Mind-Glass.dc.html', 'Flowed Metal', PAPER, body18)
