# Content for the project detail pages. Images: asset name or blob-id prefix.
ACC = '#FF5A1F'
PAGES = [
# ------------------------------------------------------------------ TOUCH
dict(slug='tactile-books', seo='Even Without Sight', kicker='01 · Touch · Care &amp; Reading',
  title=['Even without', 'sight'], sub='Tactile picture books in felt and braille for blind children, and the visits, exhibition and film around them.',
  c='#14205C', t='#FFF3DE', a='#FFC93C', a2=ACC, hero='cut_book_closed', hero_alt='A finished tactile felt book',
  meta=[('Role', 'Activities leader &amp; organiser'), ('Club', 'Care &amp; Reading, 100+ members'), ('Partner', 'ABF, a Beijing NGO for visually impaired children'), ('Output', '3 books · 10+ visits · exhibition · short film')],
  intro_plain='Tactile picture books for blind children, designed and hand-sewn in felt and braille.',
  intro='Every week, each volunteer in our club tutors one blind child online, and the same pairs stay together year after year. <em>I led 30+ members to design and hand-sew tactile picture books</em> in felt and braille, so the stories could be read with fingertips.',
  facts=[(50, '', '+', 0, 'long-term reading pairs, every week'), (30, '', '+', 0, 'members sewing tactile books'), (10, '', '+', 0, 'visits to the children'), (2, '¥', 'k+', 0, 'raised for materials')],
  blocks=[
    ('two', '01', 'The Kingdom of Shapes', ['Each book is a story set in the Kingdom of Shapes. In the first, Jianjian the triangle crosses town to a New Year concert, and every scene hides a triangle to find by touch. In the second, Fangfang the square turns into something new on every page: a flying carpet, a car, a drum, a gem.',
      'Each spread pairs a felt scene with a braille story card. A raised-line icon on the card tells the child which shape to find next.'], fig('books_grid', 'The finished books, page by page', 'Book 1 &amp; 2', ar='1/1'), False),
    ('grid', '02', 'Drawn before it was sewn', 'Before any felt was cut, I drew every spread in pencil: the layout, the loose parts, the joints in section and a cutting list.', 3, '4/3',
      [fig('sk_orig2', 'Rods that fold into a triangle and a 4', 'Sketch 02', 'contain'), fig('sk_orig5', 'The dress, drawn in parts', 'Sketch 05', 'contain'), fig('sk_orig6', 'The tree and its cutting list', 'Sketch 06', 'contain')]),
    ('steps', '03', 'How a page is made', 'Everything for one page was packed into a kit, so every club member could make a spread at home.',
      [('Measure &amp; mark', 'Shapes are ruled onto the felt before anything is cut.'), ('Cut the felt', 'Each scene piece is cut by hand.'), ('Sew the strips', 'Felt strips are stitched down to make edges a finger can trace.'), ('Fix the braille card', 'The story card is fixed opposite the scene.')], True),
    ('grid', '', '', '', 4, '1/1',
      [fig('c3ffc4ba', 'Measuring and marking', '01'), fig('95e2a121', 'Cutting the felt', '02'), fig('cfe0c0c8', 'Sewing the strips', '03'), fig('6dcdf455', 'Fixing the braille card', '04')]),
    ('grid', '04', 'Rules I designed by', 'Every shape is raised in felt strips, metal or stitched edges. Something on each page spins, rings or lights up. Nothing is loose: thread ends are covered and small parts are sewn or sealed.', 4, '3/2',
      [fig('50718ba5', 'Triangle Town: rods a child can lift and rearrange', 'B1 · 01'), fig('4db6d2ba', 'A real metal triangle the child can strike', 'B1 · 07'), fig('5c992d91', 'A rattle drum wrapped in felt', 'B2 · 04'), fig('4c6f25f7', 'Real backpack buckles to clip together', 'B2 · 07')]),
    ('two', '05', 'The visits', ['We have visited the children more than ten times. Each visit starts with ice-breaker games, then a workshop such as <i>My Little Planet</i>, where children paint with materials they can feel. We play, read the books together and interview the NGO teachers, and we filmed one visit as a short documentary.',
      'Because each child keeps the same volunteer week after week, the reading continues long after the visit ends.'], fig('visit_group', 'The volunteer team on a visit to the NGO', 'ABF, Beijing'), True),
    ('grid', '', '', '', 3, '4/3',
      [fig('kids2_hd', 'Reading the books by touch', 'Visit'), fig('b7776dd6', '<i>My Little Planet</i>: paintings made with textures', 'Workshop'), fig('cut_doll', 'A thank-you doll from the NGO teachers', 'Gift', 'cut')]),
    ('quote', '"Let the warmth of your fingertips become the light that helps blind children perceive the world."', 'Exhibition poster'),
    ('grid', '06', 'The exhibition', 'We closed the project with a club exhibition: five hands-on stations on braille, the shoes and canes blind people use, facts about blindness, our documentary and a table of tactile materials. More than 60 visitors came over a week.', 3, '4/3',
      [fig('d4e67f78', 'Visitors at the exhibition', 'Exhibition'), fig('53ce5d0d', 'A visitor reading the books', 'Exhibition'), fig('d307e5a7', 'Tactile books on display', 'Exhibition')]),
    ('notes', '07', 'What visitors wrote', '', [('"I like that you let visitors touch and interact instead of simply reading about blindness."', 'A teacher'), ('"It made me wonder what everyday objects would feel like if I could only understand them through touch."', 'A classmate'), ('"Consider adding feedback from visually impaired users themselves to strengthen the exhibition."', 'A classmate'), ('"You could explain more clearly how each texture helps a blind child understand the story."', 'A classmate')]),
  ]),
# ------------------------------------------------------------------ SIGHT
dict(slug='miniature-house', seo='A House in Miniature', kicker='02 · Sight · Craft',
  title=['A house in', 'miniature'], sub='A whole home, small enough to sit on a desk.',
  c='#F7F5F0', t='#141414', a='#7A1F2B', a2='#7A1F2B', hero='cut_house_pano', hero_alt='The miniature house, full view',
  meta=[('Medium', 'Paper, wood, fabric, clay'), ('Rooms', 'Study, dressing room, living room, kitchen, dining room'), ('Scale', 'Desktop'), ('Made by', 'Amy Hu, by hand')],
  intro_plain='A furnished miniature home, built by hand with more than 200 parts.',
  intro='The tactile books asked how a story can be read by hand. This project asks the opposite question: <em>how much can a world hold when it is read only by the eye?</em> I shrank a whole home onto a desktop.',
  facts=[(5, '', '+', 0, 'rooms on one continuous floor'), (10, '', '+ hrs', 0, 'build time'), (200, '', '+', 0, 'hand-made parts')],
  blocks=[
    ('steps', '01', 'How it was built', '', [('Plan the floor', 'Five rooms on one level, with the bed lofted above the kitchen.'), ('Build the shell', 'Walls, floor and loft go up first and must be square, or nothing inside sits straight.'), ('Make the furniture', 'Bookcase, desk, bed, sofa and cabinets, assembled piece by piece with tweezers and glue.'), ('Dress every room', 'Bedding, a towel on the rail, food on the plates: the details that make it look lived in.')], False),
    ('two', '02', 'The study', ['A desk and a full bookcase give the house someone\'s habits: tiny printed books, a desk lamp, brushes and a chair pulled up to work.'], fig('ef01523c', 'The study', 'Room 01'), False),
    ('two', '03', 'Moon window', ['A round window frames the living room like a view in a Chinese garden. Painted branches climb the walls and a screen glows with a mountain sunset.'], fig('419d9438', 'The moon window', 'Room 03', 'cut'), True),
    ('grid', '04', 'Look closer', '', 4, '1/1',
      [fig('d90bc1b8', 'Dressing room: a yellow towel, a basin, slippers', 'Room 02'), fig('f83b583b', 'Kitchen, under the loft bed', 'Room 04'), fig('6920bde1', 'Dinner already served', 'Room 05', 'cut'), fig('9e30caed', 'A tea set smaller than a fingernail', 'Detail', 'cut')]),
    ('quote', 'Making it small is not the hard part. The hard part is making every room <i>believable</i>.', 'On scale, surface and light'),
  ]),
# ------------------------------------------------------------------ TASTE
dict(slug='physics-of-baking', seo='The Physics of Baking', kicker='03 · Taste · A book I wrote',
  title=['The physics', 'of baking'], sub='Twelve months of recipes, science and self. Written, photographed, designed and published by me.',
  c='#3A2014', t='#FFF3DE', a='#FFB54A', a2='#B5541E', hero='00879407', hero_alt='Cover of The Physics of Baking', hero_photo=False,
  meta=[('Format', '38-page paperback'), ('Published', 'Amazon KDP'), ('Roles', 'Baker, photographer, writer, designer'), ('Dedication', 'For my grandfather')],
  intro_plain='A 38-page baking book pairing each month\'s recipe with the physics that makes it work.',
  intro='Each month pairs one recipe with a page on the physics that makes it work: <em>how whipped egg whites hold air, why folded butter turns into flaky layers, when a crust begins to brown.</em>',
  facts=[(38, '', '', 0, 'pages, all designed by me'), (12, '', '', 0, 'recipes and experiments'), (1, '', '', 0, 'book on sale on Amazon')],
  blocks=[
    ('quote', '"For my grandfather, whose hearing challenges first taught me to notice the quiet details of everyday life."', 'From the dedication'),
    ('list', '01', 'What happens as the temperature rises', 'The science pages follow the oven from cold butter to caramel.',
      [('34 °C', 'Butter melts'), ('62 °C', 'Egg whites set: proteins unfold and bond'), ('70 °C', 'Starch gelatinises'), ('100 °C', 'Water turns to steam, ~1,700× the volume: oven spring'), ('150 °C', 'Maillard browning'), ('170 °C', 'Caramelisation: sugar itself breaks down')]),
    ('grid', '02', 'One year, twelve experiments', 'Foams, emulsions, heat transfer, starch and fat: twelve ways physics ends up on a plate.', 4, '1/1',
      [fig('33b86b6d', 'Coconut balls: egg-white proteins set', 'Jan', 'cut'), fig('b12473c2', 'Croissants: lamination makes layers', 'Feb', 'cut'), fig('c64714e8', 'Bread: yeast makes the gas', 'Mar', 'cut'), fig('6d7202b0', 'Lemon cheesecake: an emulsion', 'Apr', 'cut'),
       fig('a5508103', 'Macarons: a meringue foam', 'May', 'cut'), fig('d4b88771', 'Chiffon: whipped whites trap air', 'Jun', 'cut'), fig('6901efba', 'Matcha scones: cold butter, flaky crumb', 'Jul', 'cut'), fig('3e9f3b49', 'Egg tarts: heat from outside in', 'Aug', 'cut'),
       fig('e434589d', 'Mung bean cake: starch sets', 'Sep', 'cut'), fig('9d7c260e', 'Donuts: fast heat transfer', 'Oct', 'cut'), fig('ddf73025', 'Basque cheesecake: a steep gradient', 'Nov', 'cut'), fig('2f09950c', 'Butter cookies: viscosity sets the spread', 'Dec', 'cut')]),
    ('two', '03', 'A page, opened', ['February is <i>Patience</i>: croissants, and the physics of lamination. Butter and dough are folded again and again until hundreds of thin layers alternate; in the oven, water in the butter turns to steam and pushes the layers apart.'], fig('406150ef', 'February: Patience, croissants', 'Book page', 'contain'), False),
    ('steps', '04', 'From kitchen to Amazon', '', [('Bake &amp; measure', 'Every recipe tested at home.'), ('Photograph', 'Every photo taken by me.'), ('Explain the science', 'One physics page per month.'), ('Design &amp; publish', '38 pages laid out, then published on Amazon KDP.')], True),
  ]),
# ------------------------------------------------------------------ SOUND & MOTION
dict(slug='guzheng-taekwondo', seo='Guzheng & Taekwondo', kicker='04 · Sound &amp; Motion',
  title=['Sound &amp;', 'motion'], sub='Performing the guzheng on stage, and eight years of taekwondo on the mat.',
  c='#E1262D', t='#FFF3DE', a='#14205C', a2='#E1262D', hero='cut_guzheng', hero_alt='Amy playing the guzheng',
  meta=[('Sound', 'Guzheng soloist, duets, ensemble · voice'), ('Motion', 'Taekwondo black belt · Beijing gold'), ('Coaching', 'Assistant instructor since Grade 5'), ('Stage', 'School gala, Grade 10 · public performance, Grade 11')],
  intro_plain='Guzheng performance and taekwondo: a black belt, a Beijing gold medal and years of coaching.',
  intro='I play the guzheng, the 21-string Chinese zither, as a soloist, in duets and with an ensemble. <em>On the mat, eight years of taekwondo</em> have given me a black belt, a Beijing gold medal and a class of younger students to coach.',
  facts=[(21, '', '', 0, 'strings on the guzheng'), (8, '', '', 0, 'years of taekwondo'), (1, '', '', 0, 'Beijing gold medal'), (50, '', '+', 0, 'younger students coached')],
  blocks=[
    ('two', '01', 'Sound', ['I perform as a soloist, in duets and with an ensemble, and I sing on the school stage. I performed at our school gala in the spring of Grade 10 and at the school\'s public performance in the autumn of Grade 11.'], fig('45d5c449', 'Guzheng duet on stage', 'Grade 10 gala'), False),
    ('grid', '', '', '', 2, '4/3', [fig('3bd92905', 'Guzheng ensemble, outdoors', 'Ensemble'), fig('36ddc2c8', 'Singing on stage with friends', 'Voice')]),
    ('two', '02', 'Motion', ['Eight years of taekwondo and a Beijing gold medal. Since Grade 5 I have also been an assistant instructor at Shangdi Youth Taekwondo Academy, coaching more than 50 younger students in forms, kicks, sparring and discipline.'], fig('a2211f55', 'Competition bout', 'Beijing'), True),
    ('grid', '', '', '', 2, '4/3', [fig('c21c06d3', 'Leading a class of young students', 'Coaching'), fig('cut_tkd2', 'In a taekwondo stance', 'Black belt', 'cut')]),
  ]),
# ------------------------------------------------------------------ PHYSICS TOURNAMENTS
dict(slug='physics-tournaments', seo='Physics Tournaments: IYPT & CYPT', kicker='05 · Mind · IB Extended Essay · IYPT · CYPT',
  title=['Coupled', 'pendulums'], sub='Energy transport and localization in a chain of magnetically coupled pendulums, and two more problems I reported at CYPT 2026.',
  c='#1B2FA8', t='#F3F0E8', a='#FFB4A3', a2='#D9432E', hero='cut_ee_rig', hero_alt='My 3D-printed magnetic pendulum rig',
  meta=[('Role', 'Team captain · reporter'), ('Tournaments', 'IYPT Macao team · CYPT 2026'), ('Research', 'IB Physics Extended Essay'), ('Community', 'Founder of Wavefront, our school physics lab')],
  intro_plain='A Lagrangian model of a chain of magnetically coupled pendulums, and CYPT problems on electrical damping and levitation control.',
  intro='A chain of magnetic pendulums is a desktop analogue of atoms in a crystal trading energy. <em>I built the rig, filmed every trial and compared the measured normal modes with a Lagrangian model</em>: they agreed to within about 1.4%.',
  facts=[(1.37, '', '%', 2, 'mean model–experiment difference'), (5, '2–', '', 0, 'pendulums in a chain'), (3, '', '', 0, 'tournament problems I reported'), (100, '', '+', 0, 'trials on my own rig')],
  blocks=[
    ('two', '01', 'The question', ['How do magnet strength, spacing, length and release angle shift the chain\'s normal-mode frequencies, and how does that decide whether energy spreads through the chain, returns to a few modes, or stays trapped?',
      'I designed and 3D-printed the apparatus: a rigid top rail, sliding PETG brackets, bearing-mounted arms and magnets in baskets. Each trial was filmed at 30 frames per second, tracked in Tracker, and the eigenfrequencies extracted by Fourier transform.'], fig('ee_rig', 'My apparatus: brackets set the spacing; bearings and baskets hold the magnets', 'Rig'), False),
    ('grid', '02', 'What the model showed', 'The nearly in-phase mode stays controlled by gravity, while higher modes rise with magnetic moment and fall strongly with spacing. Larger release angles soften the frequencies.', 3, '4/3',
      [fig('40c72e4d', 'Normal modes of a five-pendulum chain', 'Model', 'contain'), fig('51433956', 'Theory against experiment, in time and frequency', 'Result', 'contain'), fig('16f7d25b', 'Energy spreading, recurrence and self-localization', 'Simulation', 'contain')]),
    ('two', '03', 'Electrical damping', ['A magnet on a spring oscillates inside a coil wired to a resistor. I modelled the flux and the mutual-inductance gradient, coupled the circuit to the motion, and predicted that damping peaks near 2,700 coil turns, falls as 1/R and grows with the square of the magnetic moment. My data followed all three trends.'], fig('cy_ed_rig_cut', 'My electrical damping rig', 'CYPT · Problem 2', 'cut'), True),
    ('two', '04', 'Levitation control', ['Pyrolytic graphite floats over a checkerboard of magnets. A laser heats one edge; graphite\'s susceptibility depends on temperature, so the force becomes uneven and the sheet should slide. I built field, temperature and motion models, bought and set up the laser, the gantry and the magnets, and found that my N52 magnets held the sheet too firmly for a 1.6 W beam. The model tells me what to change next.'], fig('cy_ph_laser', 'The laser on a 2-D gantry over the magnet array', 'CYPT · Problem 9'), False),
    ('grid', '05', 'Leading the team', 'As captain I led our discussions: we took each problem apart into physics, model and experiment, argued over every assumption and rehearsed the opposition and review rounds together. At school I founded Wavefront, our physics lab and community, and tutor younger students for tournaments.', 3, '4/3',
      [fig('cy_ph_discuss', 'Leading a team discussion', 'Captain'), fig('cy_ph_present', 'Reporting Electrical Damping', 'CYPT 2026'), fig('cy_ph_team', 'The whole team at work', 'Team')]),
  ]),
# ------------------------------------------------------------------ SMARTHEARING
dict(slug='smarthearing', seo='SmartHearing', kicker='05 · Mind · Peking University, Institute for AI',
  title=['Smart', 'hearing'], sub='Scene-adaptive hearing assistance: a hearing aid that decides which sound matters, and enhances it.',
  c='#5E1A14', t='#FFFFFF', a='#FFB4A3', a2='#C2412D', hero='lt_hearing', hero_alt='SmartHearing hearing-aid prototype', hero_photo=True,
  meta=[('Role', 'Product design lead · equal-contribution author'), ('Lab', 'Peking University, Institute for AI'), ('Output', 'Patent · ICASSP 2027 submission'), ('Why', 'My grandfather\'s hearing loss')],
  intro_plain='An AI hearing aid that uses a large audio language model to decide which sound in a scene matters most.',
  intro='Conventional hearing aids amplify speech, but which sound matters most, <em>a siren, an alarm, a scream,</em> depends on the scene. SmartHearing listens to the scene, decides what you need to hear, and brings that sound forward.',
  facts=[(50.5, '', '%', 1, 'of trials rated most salient'), (101, '', '', 0, 'listening-test participants'), (1.14, '+', ' dB', 2, 'SI-SDRi gain from our Adapter'), (1, '', '', 0, 'patent held')],
  blocks=[
    ('two', '01', 'Perceive, decide, act', ['A large audio language model describes each sound in the scene: what it is, how dangerous, how relevant. A Query-space Adapter translates those descriptions into the language a sound separator understands, and the separator extracts each source so the device can raise warnings, keep useful ambience and suppress noise.'], fig('sh_arch_t', 'System architecture: perception path, Adapter, execution path', 'Fig. 1', 'contain'), False),
    ('two', '02', 'Why the scene matters', ['A car horn in the street, speech in a restaurant, a crying infant at home: the same device must enhance different sounds in different places. On 145 unseen mixtures the gains held, and in a 101-person listening test SmartHearing was rated most salient in 50.5% of trials, against 28.1% and 21.5% for the baselines.'], fig('sh_scenes', 'The target sound depends on the scene', 'Fig. 2'), True),
    ('quote', 'My grandfather\'s hearing taught me to notice quiet details. This project is about the loud ones that must never be missed.', 'Why it matters to me'),
  ]),
# ------------------------------------------------------------------ METALLIC GLASS
dict(slug='metallic-glass', seo='Flowed Metal', kicker='05 · Mind · Chinese Academy of Sciences, Institute of Mechanics',
  title=['Flowed', 'metal'], sub='Micro-particle impacts on metallic glasses under high temperature.',
  c='#1D2226', t='#FFFFFF', a='#F2A16E', a2='#C4521F', hero='lab_setup', hero_alt='The laser-induced particle impact platform', hero_photo=True,
  meta=[('Role', 'First author'), ('Lab', 'Institute of Mechanics, CAS'), ('Supervisor', 'Prof. Minqiang Jiang'), ('Recognition', 'ISEF Beijing qualifier')],
  intro_plain='Laser-launched micro-particle impacts show that a Pd-based metallic glass softens and flows at high temperature.',
  intro='Glass shatters; metal bends. <em>A metallic glass is both.</em> I fired 30 µm particles at hundreds of metres per second into a Pd-based metallic glass at 25, 100 and 200 °C to find out whether heat makes it harder, like a metal, or softer, like a glass.',
  facts=[(10.39, '−', '%', 2, 'dynamic yield strength, 25 → 200 °C'), (5, '', ' M fps', 0, 'high-speed camera'), (3, '', '', 0, 'test temperatures'), (100, '', '+', 0, 'impact tests')],
  blocks=[
    ('two', '01', 'The experiment', ['A 7 ns, 532 nm laser pulse ablates a gold film and launches a silica particle at 1–1000 m/s; a camera at up to five million frames per second records the impact and rebound. A PID controller holds the target within ±1 K. I prepared and characterised every sample, ran every impact and analysed the craters by SEM and confocal microscopy.'], fig('fm_hs25', 'High-speed frames: the particle falls in and rebounds', 'In situ', 'contain'), False),
    ('grid', '02', 'Solid at 25 °C, fluid at 200 °C', 'At high temperature the glass dissipates more energy, its dynamic yield strength falls by 10.4%, and the crater rim splashes outward like a viscous fluid.', 3, '1/1',
      [fig('bmg_sem25', 'Crater at 25 °C: a regular rim', 'SEM'), fig('bmg_sem200', 'Crater at 200 °C: splash-like pile-up', 'SEM'), fig('bmg_cor', 'Coefficient of restitution against impact speed', 'Data', 'contain')]),
    ('two', '03', 'Why: shear transformations', ['I built a quarter-symmetric ABAQUS model with 1.35 million elements and a coupled shear-transformation / free-volume law. It matched the measured crater and showed why: at 200 °C contact lasts longer, stress is lower and many more shear transformations activate.'], fig('fm_sim', 'Field-averaged stress, plastic strain and STZ density', 'Simulation', 'contain'), True),
  ]),
# ------------------------------------------------------------------ CURAWAVE
dict(slug='curawave', seo='Curawave', kicker='05 · Mind · Conrad Challenge',
  title=['Cura', 'wave'], sub='A wave-bionic soft robotic mattress that slides a patient sideways onto another bed, with no one lifting.',
  c='#0B3B45', t='#FFFFFF', a='#8FE3D8', a2='#0F7C7A', hero='cw_units', hero_alt='Cast silicone mattress units', hero_photo=True,
  meta=[('Role', 'CTO'), ('Competition', 'Conrad Challenge'), ('Built', 'Moulds, silicone units, valves, Arduino'), ('Why', 'My own weeks on an injured leg')],
  intro_plain='A mattress of inflatable silicone units that tilt in alternating groups to slide a patient sideways onto another bed.',
  intro='Among 1,200 post-operative patients in one study, 15% had complications related to being moved. <em>Curawave moves a patient the way a wave moves a boat</em>: soft units tilt left and right in alternating groups and slide the patient horizontally onto the next bed.',
  facts=[(360, '', '', 0, 'units in the full 18 × 20 design'), (3, '', '+', 0, 'prototype generations'), (20, '', '+', 0, 'parts printed or cast'), (100, '', '+', 0, 'people pitched to')],
  blocks=[
    ('two', '01', 'How one unit moves', ['Each unit has a hollow silicone inflation layer, a non-stretch cotton confining layer and a silicone base. Because the confining layer stretches less, the unit tilts sideways when inflated. Neighbouring groups inflate in turn, so a sideways wave carries the patient across.'], fig('cw_principle', 'How one unit tilts and pushes', 'Principle', 'contain'), False),
    ('steps', '02', 'How we built it', '', [('Model the moulds', 'Autodesk Fusion: bases, top, bottom and core.'), ('Cast and test', 'Moulds 3D-printed; silicones of different thickness compared.'), ('Valves + code', 'Solenoid valves switch the pump; an Arduino times them.'), ('1 × 4 prototype', 'Air split four ways, each group on its own valve.')], True),
    ('grid', '03', 'From prototype to plan', '', 3, '16/9', [fig('cw_circuit', 'Pump, valves and Arduino wiring', 'Hardware'), fig('cw_slide09', 'The layers of one unit', 'Design', 'contain'), fig('cw_slide16', 'The Curawave brand', 'Brand', 'contain')]),
  ]),
# ------------------------------------------------------------------ LINGTONG
dict(slug='lingtong', seo='Lingtong Future Technology', kicker='05 · Mind · Entrepreneurship',
  title=['Lingtong', 'Future Tech'], sub='The human-centred assistive technology company I founded to turn research into products.',
  c='#33244D', t='#FFFFFF', a='#E0A93B', a2='#33244D', hero='lt_logo', hero_alt='Lingtong logo', hero_small=True,
  meta=[('Role', 'Founder &amp; CTO'), ('Team', 'About five people'), ('Raised', 'USD 100k+'), ('Trademarks', 'Filed July 2026, CNIPA')],
  intro_plain='Lingtong Future Technology: an assistive technology startup built around SmartHearing and Curawave.',
  intro='A paper proves an idea works; <em>only a product reaches the person who needs it.</em> Research at Peking University and the Conrad Challenge gave us two working prototypes, so I founded Lingtong to carry them further.',
  facts=[(100, '$', 'k+', 0, 'raised so far'), (2, '', '', 0, 'product lines, one R&amp;D team'), (2, '', '', 0, 'trademark applications'), (5, '¥', '–8 M', 0, 'first round planned')],
  blocks=[
    ('list', '01', 'Two products, one focus', 'For the first 18 months, 70–80% of our resources go to SmartHearing; Curawave continues as the second growth curve.',
      [('SmartHearing', 'AI hearing system that decides which sound you need to hear. Patent filed.'), ('Curawave', 'Wave-bionic transfer mattress, three prototype generations, for hospitals and care homes.')]),
    ('list', '02', 'Three revenue streams', '',
      [('Own-brand devices', 'Device, app and long-term service; basic hearing never behind a subscription.'), ('Institutional solutions', 'Hearing centres, care homes and hospitals: equipment, training and maintenance.'), ('Technology licensing', 'An Auditory Decision Engine SDK for earbuds, hearing aids and smart glasses.')]),
    ('steps', '03', 'Three-year plan', '', [('0–6 months', 'Research prototype to wearable SmartHearing; device-classification advice.'), ('6–12 months', 'Pilots with 100–300 users and 3–5 partner institutions.'), ('12–24 months', 'Design freeze, registration path, first paid sales.'), ('24–36 months', 'National channels; licensing begins.')], True),
    ('grid', '04', 'Trademarks', 'Application No. 92712127 (Class 42) was accepted on 20 July 2026; No. 92712148 passed preliminary examination and was published on 27 September 2026.', 2, '3/4',
      [fig('lt_tm1', 'Acceptance notice', 'CNIPA', 'contain'), fig('lt_tm2', 'Preliminary approval notice', 'CNIPA', 'contain')]),
  ]),
# ------------------------------------------------------------------ OPTICS
dict(slug='optics', seo='Experimental Optics', kicker='05 · Mind · Peking University, Institute of Physics',
  title=['Light,', 'measured'], sub='Polarisation control and twelve experimental optics reports, then Raman and laser systems in a research lab.',
  c='#0F2A1E', t='#FFFFFF', a='#9BE7B4', a2='#2F7D4F', hero='op_ph4', hero_alt='Laser and spectrometer bench', hero_photo=True,
  meta=[('Role', 'Nonlinear optics research intern'), ('Lab', 'Peking University, Institute of Physics'), ('Reports', '12 full lab reports'), ('Systems', 'Raman, lasers, polarisation')],
  intro_plain='Twelve experimental optics reports and research-lab work on Raman and laser systems and polarisation states.',
  intro='I worked through twelve classic optics experiments and wrote each up in full. <em>The measurements agree closely with reference values</em>: a He-Ne wavelength of about 633 nm against 632.8 nm, and Malus\'s law within 0.4% at 45°.',
  facts=[(12, '', '', 0, 'optics experiments, each a full report'), (20, '', '+', 0, 'polarisation states tested'), (633, '≈ ', ' nm', 0, 'He-Ne wavelength, measured'), (0.4, '', '%', 1, 'Malus\'s law deviation at 45°')],
  blocks=[
    ('list', '01', 'Twelve experiments', 'Every report ended with an error analysis: read many fringes at once, both sides of a pattern, and turn screws in one direction only.',
      [('Thin lens', 'f = 100.0 mm by the conjugate method'), ('Newton\'s rings', 'Lens radius ≈ 0.85 m'), ('Air wedge', 'Sheet thickness ≈ 74 µm'), ('Young\'s double slit', 'He-Ne wavelength ≈ 633 nm'), ('Diffraction grating', 'Mercury green line ≈ 546 nm'), ('Malus\'s law', 'I/I₀ = 0.502 at 45°'), ('Abbe refractometer', 'Water 1.3330, sugar solution 1.3474'), ('Holography', 'A 3-D image rebuilt from a plate')]),
    ('grid', '02', 'In the lab', 'I built every set-up myself, then operated Raman and laser systems normally used by graduate students and tested more than twenty polarisation states of the beam.', 4, '3/4',
      [fig('op_ph1', 'My labelled sample', 'Sample'), fig('op_ph2', 'The clean-room entrance', 'Lab'), fig('op_ph3', 'An optical table I aligned', 'Bench'), fig('lab_land', 'Beside the optics', 'Me')]),
  ]),
# ------------------------------------------------------------------ MODELLING
dict(slug='modelling', seo='Mathematical Modelling', kicker='05 · Mind · IMMC · HiMCM',
  title=['Modelling', 'the world'], sub='Five modelling papers, all written by me as team captain and main modeller, and an applied mathematics journal.',
  c='#14233F', t='#FFFFFF', a='#F2AA5A', a2='#C8641E', hero='mm_cover', hero_alt='Applied Mathematics, Vol. 2', hero_photo=True,
  meta=[('Role', 'Team captain · main modeller'), ('Papers', 'Five, all written by me'), ('Awards', '3 Finalist awards'), ('Also', 'Editor, school mathematics journal')],
  intro_plain='Five mathematical modelling papers for IMMC and HiMCM, and an applied mathematics journal.',
  intro='Turn a messy real problem into variables, assumptions and a model you can test, <em>then explain it clearly.</em> As captain I split each problem into sub-models, built the core model and wrote the paper against the deadline.',
  facts=[(5, '', '', 0, 'papers, all written by me'), (3, '', '×', 0, 'Finalist awards'), (2, 'Vol. ', '', 0, 'journal issue on IMMC')],
  blocks=[
    ('two', '01', 'Saving the Panama Canal\'s water', ['IMMC 2024. From the water exchange between lock chambers and water-saving basins I derived the optimal number and size of basins, then combined energy, maintenance, water, labour and material costs into one cost model.'], fig('70058dcf', 'Water exchange between lock and basins', 'IMMC 2024', 'contain'), False),
    ('two', '02', 'Teaching a robot to jump rope', ['IMMC 2025. I described the spinning rope as a catenary using the Jacobi elliptic function sn, drew it at every moment in MATLAB, and found the jump speeds, times and rope lengths that make a jump possible.'], fig('ff4b7949', 'The rope\'s 3-D path through one turn', 'IMMC 2025', 'contain'), True),
    ('two', '03', 'Sweeping a burning building', ['HiMCM 2025, Finalist. A cellular automaton models fire, smoke and occupants; mixed-integer programming finds the fastest route and number of responders to clear every room.'], fig('226909ee', 'Simulated fire spread over time', 'HiMCM 2025', 'contain'), False),
    ('two', '04', 'Is Friday the 13th unlucky?', ['IMMC 2026. A Boltzmann-style expectation model and information theory turned 25 years of disasters into "unluckiness". Friday the 13th averaged 5.56 against a maximum of 18.21: the superstition does not hold.'], fig('f0746e71', 'Predicted unluckiness of every date in 2025', 'IMMC 2026', 'contain'), True),
    ('two', '05', 'Guarding Etosha', ['IMMC 2026. Risk mapping, topological decomposition, Snake-algorithm patrol loops and a Kalman-filter revisit interval for rangers in a vast national park.'], fig('c23a2b81', 'Risk map of Etosha National Park', 'IMMC 2026', 'contain'), False),
  ]),
]
